### ISSUE TITLE
Investigate algorithms for testing degeneracy of normal form games

### ISSUE THREAD

**Issue by drvinceknight** [theref/sage-game-theory#101]
This is an issue to keep track of the conversation and reference about the algorithms before decisions are made as to what will be implemented.

**Comment by theref** [comment]
http://www.maths.lse.ac.uk/personal/stengel/ETissue/ARSvS.pdf

http://web.stanford.edu/~saberi/lecture4.pdf

**Comment by theref** [comment]
http://web.stanford.edu/~saberi/lecture4.pdf

**Comment by theref** [comment]
i've created a branch and started writing tests 332b366

any tests will currently fail.

**Comment by drvinceknight** [comment]
:+1:

**Comment by theref** [comment]
for reference later: http://e-collection.library.ethz.ch/eserv/eth:3346/eth-3346-01.pdf
page 23

**Comment by drvinceknight** [comment]
That looks like a great way to go. There will be things directly in sage for computing linear independence of rows etc...

**Comment by drvinceknight** [comment]
Here's another version of that paper/book chapter: http://www.maths.lse.ac.uk/personal/stengel/TEXTE/nashsurvey.pdf

I don't know which one is more up to date.

**Comment by theref** [comment]
Prisoner's Dilemma
![screen shot 2015-06-17 at 15 08 02](https://cloud.githubusercontent.com/assets/4128101/8209033/acaf736e-1502-11e5-9bfd-f97ecaec44d7.png)

**Comment by drvinceknight** [comment]
First of all: how did you do that?

Second of all, are you running this on big games etc...? How many games?

**Comment by theref** [comment]
a lovely little profiling package: https://github.com/what-studio/profiling
if you want to install it within sage... `./sage -pip install git+https://github.com/what-studio/profiling.git`

and it's only one run through, i'm doing with a bigger game now and will keep posting them
i'll also do some non-degenerate ones

**Comment by theref** [comment]
The larger 4x4 test example
![screen shot 2015-06-17 at 15 15 03](https://cloud.githubusercontent.com/assets/4128101/8209229/b72d5a44-1503-11e5-8d22-60c094bc601e.png)

**Comment by drvinceknight** [comment]
Sweet. Have you pushed the code for the `def` algorithm?

**Comment by theref** [comment]
3x2 example from various papers
![screen shot 2015-06-17 at 15 19 49](https://cloud.githubusercontent.com/assets/4128101/8209348/659184de-1504-11e5-967a-0d97549c024a.png)

> Sweet. Have you pushed the code for the def algorithm?

no, i've left it on my own private branch for now. I can push that branch up though?
Looking like we'll go with LA anyway.

**Comment by drvinceknight** [comment]
Would be cool to look at it (just out of curiosity). 

How does the profiler work? Is there any chance that the results are different if you called the functions in the opposite order?

**Comment by theref** [comment]
I have no idea how it works :D 
I doubt it would make a difference but i'll check

**Comment by drvinceknight** [comment]
Yeah just to confirm.

**Comment by drvinceknight** [comment]
Could you run some old school `timeit`'s just to confirm as well.

**Comment by theref** [comment]
10 runs for each of these...
![screen shot 2015-06-17 at 16 06 15](https://cloud.githubusercontent.com/assets/4128101/8210640/d5059f70-150a-11e5-83f3-76655087fe77.png)
![screen shot 2015-06-17 at 16 08 52](https://cloud.githubusercontent.com/assets/4128101/8210715/2e941f26-150b-11e5-9a8f-929473079aa6.png)

![screen shot 2015-06-17 at 16 03 54](https://cloud.githubusercontent.com/assets/4128101/8210589/ab9dd08a-150a-11e5-8d7d-5183def5d7d8.png)
