### ISSUE TITLE
Start working on Extensive Form Games, working on structure of classes and looking at implementing graph theory

### ISSUE THREAD

**Issue by hhlorrimore** [theref/sage-game-theory#104]
![image](https://cloud.githubusercontent.com/assets/12892153/8228974/e65b32f8-15aa-11e5-816e-2a548f5e8877.png)
Here's some of the classes we want to include:
- a class for nodes, probably including what we call the node and possibly what children and parents it has.
- a tree class, we're not 100% sure what we're putting here just yet, but this may come later after I look at some graph theory stuff
- a class for chance nodes, which will be similar to normal nodes but include probabilities of the actions
- Information set class, which will simply be grouping nodes together
- Players class, though this we're not sure if we'll include this yet

Also as a side note, actions for extensive form will probably be a dictionary mapping actions to children (and the root node).

As for graph theory we might want to inherit straight from the code within sage, and make use of the `is_tree()` function as a useful check. I'll look at the code for graph theory and see if there's classes for vertices, nodes and general tree things, and see if we can use it somehow.

**Comment by drvinceknight** [comment]
This looks particularly helpful: http://programmers.stackexchange.com/questions/136216/networkx-python-is-using-a-class-for-a-node-better-practice-than-defining-mu

> Networkx allows you to have any object associated with a node.

**Comment by hhlorrimore** [comment]
Looked at networkx, looks promising, can use arbitrary classes for the nodes, which saves us some effort, so we want to have elements of the decision node in the graph nodes. So for example the following works 

```
class TestClass:
    def __init__(self, name):
        self.name = name
    def __str__(self):
        return 'Player ' + str(self.name)

a = TestClass(1)
b = TestClass(2)
c = TestClass(3)
d = TestClass(4)
e = TestClass(5)
f = TestClass(6)
g = TestClass(7)

G = Graph({a:[b,c], c:[d,e], b:[f,g]})
```

The above creates a graph (which passes the tree test), and will look like this: 
![image](https://cloud.githubusercontent.com/assets/12892153/8235495/3bd582ea-15da-11e5-969f-c0fa5697c3d8.png)

 We can work in two ways from here, we can either have the nodes know who its 'immediate family' is, and have them keep the information and build a tree out of it, or pass the nodes to a tree which knows that information for it. The overall goal for extensive form game class is that we initialise it so it inherits from the graph code within sage.

Next task is to write some tests and start building the classes for Extensive Game Form, and then go from there.

**Comment by drvinceknight** [comment]
:+1:
