### ISSUE TITLE
Raise error for invalid algorithm

### ISSUE THREAD

**Issue by theref** [theref/sage-game-theory#105]
Currently if someone were to do:

```
sage: A = matrix([[1, 1, 5], [2, 2, 0]])
sage: g = NormalFormGame([A])
sage: g.obtain_nash(algorithm='garbage')
```

sage just returns with no error raised.
correct output should be:

```
sage: g.obtain_nash(algorithm='garbage')
Traceback (most recent call last):
 ...
ValueError: garbage is not a valid algorithm.
```

Do we want to raise a new ticket for this? or just sneak it into a current one?

**Comment by drvinceknight** [comment]
> Do we want to raise a new ticket for this? or just sneak it into a current one?

Tempting, might as well keep things clean, this would not take long at all to review so just open a new ticket :+1:

**Comment by ptigwe** [comment]
I've already done this within the LP ticket

**Comment by ptigwe** [comment]
sage: g = NormalFormGame([matrix.identity(3), matrix.identity(3)])
sage: g.obtain_nash("ll")
ValueError: 'solver' should be set to 'enumeration', 'LCP', 'lp-<MILP-solver>' or 'lrs'

**Comment by drvinceknight** [comment]
:+1: Yup - cool :)
