### ISSUE TITLE
Review from Dima from Oxford visit on 2015-07-27

### ISSUE THREAD

**Issue by drvinceknight** [theref/sage-game-theory#133]
- [x] Include a certificate (return the `sigma`), by default `certificate=False`, `certificate=True` - First entry of tuple is always `True`.
- [x] Include http://arxiv.org/abs/0905.3012 in the references.
- [x] Include note that `best_response` is only implemented for two player games and then include "Row Player"/"Column Player" instead of "Player 1/Player 2".

Dima noted that `matrix(QQ,...)` would imply that code is slow.

**Comment by theref** [comment]
- [x] Docs for certificate
- [x] return which player the strategy corresponds too
