### ISSUE TITLE
In init sort all tuples of coalitions

### ISSUE THREAD

**Issue by drvinceknight** [theref/sage-game-theory#18]
Not sure if this is needed but I can imagine that someone could have a characteristic function input with something like:

```
{(A,):1, (B,):1, (C,):2, (B,A):3...}
```

Where `(B,A)` is not put in a sorted order. I wonder if that would break certain other things further down the line. A simple fix would be to sort all keys on initialisation. Something like:

```
for key in cf:
    key.sort()
```

Not sure if this is overkill, what do you reckon?

**Comment by theref** [comment]
I'lll write a test tomorrow and see what happens, if nothing breaks then we can keep it how it is

**Comment by drvinceknight** [comment]
Excellent plan.

On 4 June 2014 22:29, James Campbell notifications@github.com wrote:

> I'lll write a test tomorrow and see what happens, if nothing breaks then
> we can keep it how it is
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/theref/sage-game-theory/issues/18#issuecomment-45154294
> .

## 

Dr Vincent Knight
Cardiff School of Mathematics
Senghennydd Road,
Cardiff
CF24 4AG
(+44) 29 2087 5548

**Comment by theref** [comment]
ok, should be a simple fix involving `dict[newkey] = dict.pop(oldkey)`

**Comment by drvinceknight** [comment]
I think something like this would work slightly neater:

```
for key in dict:
    key.sort()
```

That will need a tweak to deal with tuples probably not having a sort
method. Googling 'sort all keys in a dictionary' is probably worth some
time...

**Comment by theref** [comment]
i think

```
for oldkey in dict:
    newkey = tuple(sorted(list(oldkey)))
    dict[newkey] = dict.pop(oldkey)
```

will do it

**Comment by drvinceknight** [comment]
That seems a bit messier to me (poping is not necessary) as you're creating
new keys. My method (given that Python is object based you're just move the
pointer to a sorted version) with a tweak using the right way to sort a
tuple is the way to go I expect.

V

**Comment by drvinceknight** [comment]
(Try both)

**Comment by theref** [comment]
you can't edit tuples, which includes sorting them, hence a new key has to be created

**Comment by drvinceknight** [comment]
That's why a combination is needed, so have:

```
key = sorted...(key)
```

That's neater then relabelling two things and having an old and new key as
well as the pop method.

V

**Comment by theref** [comment]
ok, i'll try it out

**Comment by drvinceknight** [comment]
Tried my way and doesn't seem to work. Go with your way: call them key and
sortedkey.
