### ISSUE TITLE
Shorten _repr_ method and create _latex_ method

### ISSUE THREAD

**Issue by theref** [theref/sage-game-theory#20]
See issue #19 for previous discussion

**Comment by drvinceknight** [comment]
The LaTeX method should be really simple. Just a representation of the characteristic function (as this is what defines the game): using `\begin{cases}`. We can then always run the `latex` command on the output of the payoff_vector in whatever format is wanted.

For `_repr_` I guess it's a question of just displaying a one liner with like 'Characteristic function game on X players'?
