### ISSUE TITLE
Do we use sage's powerset function or built in python functions

### ISSUE THREAD

**Issue by theref** [theref/sage-game-theory#22]
I'm currently producing graphs with sage to see which option produces the best results.

**Comment by drvinceknight** [comment]
Wasn't this supposed to be for permutations? (Using Sage's permutation function or itertools permutation function)

**Comment by theref** [comment]
![plot](https://cloud.githubusercontent.com/assets/4128101/3200008/c00afb60-ed74-11e3-92f9-6c3a87f2cf44.png)

Python is in purple and Sage is in red. There's really not much difference, I think its worth sticking with Sage just for readability.

**Comment by drvinceknight** [comment]
Yeah I agree.

On 6 June 2014 13:20, James Campbell notifications@github.com wrote:

> [image: plot]
> https://cloud.githubusercontent.com/assets/4128101/3200008/c00afb60-ed74-11e3-92f9-6c3a87f2cf44.png
> 
> Python is in purple and Sage is in red. There's really not much
> difference, I think its worth sticking with Sage just for readability.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/theref/sage-game-theory/issues/22#issuecomment-45330505
> .

## 

Dr Vincent Knight
Cardiff School of Mathematics
Senghennydd Road,
Cardiff
CF24 4AG
(+44) 29 2087 5548
