### ISSUE TITLE
Do we use sage's permutation function or built itertools function

### ISSUE THREAD

**Issue by theref** [theref/sage-game-theory#23]

**Comment by theref** [comment]
![nplot](https://cloud.githubusercontent.com/assets/4128101/3201469/1b8f127e-ed88-11e3-9df6-3f91531f816d.png)
Sage in Red
Python in Purple
this only makes a difference when we start getting into big games, but using python is actually more readable in this instance so i think we should stick with what we've got

**Comment by drvinceknight** [comment]
Looks good to me.
