### ISSUE TITLE
Add Mathematical definitions to docs

### ISSUE THREAD

**Issue by drvinceknight** [theref/sage-game-theory#25]
- [x] General discussion about characteristic function games
- [x] Properties of games:
  - [x] Monotone
  - [x] Supper additive
- [x] Properties of payoff vector:
  - [x] efficiency
  - [x] nullplayer
  - [x] symmetry

**Comment by drvinceknight** [comment]
I think this is done, let me know if you think anything else should be included.

**Comment by theref** [comment]
looks all good to me
