### ISSUE TITLE
Ticket #16466 will need its copy of Gambit updating if Ted's changes work

### ISSUE THREAD

**Issue by theref** [theref/sage-game-theory#37]

**Comment by drvinceknight** [comment]
Is this worth writing on trac just in case things get merged in to master and it would be better waiting?

**Comment by drvinceknight** [comment]
James, I have put the sage-integration version of gambit [here](http://www.vincent-knight.com/static/gambit/gambit-14.0.2.tar.gz). Can you check that it's ok and sort out #16466 on trac as required.

**Comment by drvinceknight** [comment]
I have also added a blurb on this [subpage](http://www.vincent-knight.com/other/) of my site. Double check that the tarbell is ok and then I'll let Ted know.

**Comment by drvinceknight** [comment]
Can we close this now or best to leave open whilst waiting for a reply on trac?

**Comment by theref** [comment]
I think leave it open for now
