### ISSUE TITLE
Implement LRS and add as an option in obtain_Nash

### ISSUE THREAD

**Issue by theref** [theref/sage-game-theory#44]

**Comment by drvinceknight** [comment]
Yeah parsing the output is an important job. Various options (try them all, figure out the best):
- dirty parsing like I did with gambit
- using something like the csv module with particular delimiters
- regular expressions
- something else (better might exists)

It'll be super important to test these rigorously. In particular cases where there are multiple 2 player strategies for any given 1 player strategy.

This might be of help `random_matrix(ZZ,5)`.

You can compare to the output of `LCP` although note that LCP _might_ not always find all the equilibrium.
