### ISSUE TITLE
Work out what happens if gambit is not installed, fix it

### ISSUE THREAD

**Issue by theref** [theref/sage-game-theory#45]

**Comment by theref** [comment]
Need to have a computer with no gambit on at all, this will probably be the Ubuntu machine

**Comment by drvinceknight** [comment]
Currently acting as a test case for this I think:

I don't have gambit on my macbook.

Checked out [Ted's sage-integraction branch](https://github.com/tturocy/gambit/tree/sage_integration) and created the relevant tarbell. Put that in upstream and tried to run `./sage -i gambit` (following [this](https://github.com/theref/sage-game-theory/blob/16333/src/sage/game_theory/installing_gambit.md) but that didn't work and sage went of and grabbed gambit online somewhere... ). Those instructions must be updated asap (I'm happy to do that once you tell me what to do).

**Comment by theref** [comment]
I haven't updated  [this](https://github.com/theref/sage-game-theory/blob/16333/src/sage/game_theory/installing_gambit.md) file yet so those steps aren't correct.

sage managed to get gambit from online? thats clever!

what happens if you try and build sage using branch 16333 without having any gambit on your machine at all?

**Comment by drvinceknight** [comment]
> sage managed to get gambit from online? thats clever!

Yeah that really surprised me too!!!

> what happens if you try and build sage using branch 16333 without having any gambit on your machine at all?

It builds but then crashes when I run sage:

```
  1 r"""
  2 2 Player normal form games
  3 
  4 This module implements 2 by 2 normal form (bi-matrix) games. A variety of
  5 operations on these games can be carried out:
  6 
  7 - Identification of (weakly) dominated strategies;
  8 - Identification of Best responses to a given strategy;
  9 - Identification of Nash Equilibrium (this is done by interfacing with Gambit);
 10 """
 11 from itertools import product
 12 from sage.misc.package import is_package_installed
 ---> 13 from gambit import Game
    global gambit = undefined
    global Game = undefined
 14 from gambit.nash import ExternalLCPSolver
 15 from sage.matrix.constructor import matrix, copy, QQ
 16 
 17 
 18 class NormalFormGame(Game):
 19     r"""
 20     An object representing a Normal Form Game. Primarily used to compute the
 21     Nash Equilibrium.
 22 
 23     INPUT:
 24 
 25     If only ``matrix1`` is provided, ``matrix2`` will be created as the
 26     negative of ``matrix1`` so that a zero-sum game is created. If a ``game``
 27     is provided, ``matrix1`` and ``matrix2`` will be generated automatically.
 28 
 29     - ``matrix1`` - a matrix representing the payoff for player1 in a 2 player
 30                     Normal Form game.
 31     - ``matrix2`` - a matrix representing the payoff for player2 in a 2 player

ImportError: No module named gambit
```

**Comment by drvinceknight** [comment]
I'm building sage by running `sage -b` there.

**Comment by theref** [comment]
Ok, I have a couple of ideas to try:
- [ ] wrap the import statement in conditionals
  - [ ] in `__init__`
  - [ ] at top of `normal_form_game.py`
- [ ] use dual inheritance and inherit from `SageObject` first
- [ ] wrap the import statement in `try` and `except` instead of conditionals
- [ ] find a way to raise a Warning instead of an Error so that Sage doesn't crash

**Comment by drvinceknight** [comment]
Yes this all sounds sensible to me. Would you rather I wait for you to implement that so that I can test it before installing gambit on this machine? (Which I still don't know how to do).

Once you've done it and it works, we'll send an email to sage-devel asking if this is the right way to go...

**Comment by drvinceknight** [comment]
Throwing `try` and `except` statements around more or less everything now lets installation run: https://github.com/theref/sage-game-theory/tree/vdev

What I've done needs to be severely cleaned up if it is indeed the way to go. I'm wondering if a more elegant solution is some sort of if statement in the make script, so that it only tries to grab normal_form_games.py if gambit is installed... **Actually, I'm pretty sure that's the way to go.**

**Comment by drvinceknight** [comment]
This is now fixed with `all.py` now reading:

```
from sage.misc.package import is_package_installed
from cooperative_game import CooperativeGame
if is_package_installed('gambit'):
    from normal_form_game import *
```

I'll close this issue now.
