### ISSUE TITLE
Implement automatic scaling of non integer input matrices.

### ISSUE THREAD

**Issue by drvinceknight** [theref/sage-game-theory#50]

**Comment by theref** [comment]
I've got this working for rational numbers.
Any ideas for non rationals? or is that a step too far?

**Comment by drvinceknight** [comment]
The only way we could do this for irrationals would be to get the
irrationals to a given level of precision and then use you scaler. I'm not
terribly sure this is worth implementing (it's a lot of effort for some
very weird cases).

Having some error catches in there is worth doing though. Also, can LRS
handle irrationals? If so just point the user there in the error message
perhaps...

I've just looked through the code I grabbed before going offline (not sure
when this message will get to GitHub). So before the commit relevant to
this message. All looks good (I have one or two questions) and will check
everything else asap.

**Comment by drvinceknight** [comment]
Re-opening as I have a hunch it could be tidier. Want to talk about it.

**Comment by theref** [comment]
Have opened a new ticket for this, #66
