### ISSUE TITLE
Sort our minimisation possibility

### ISSUE THREAD

**Issue by drvinceknight** [theref/sage-game-theory#53]
If a game is defined in terms of utility minimisation, this should be passable as an option to obtainNash.

Simply taking the opposite of the payoff matrices takes care of this.

**Comment by theref** [comment]
what do you mean by opposite?

**Comment by drvinceknight** [comment]
minus A

**Comment by theref** [comment]
ok, that's simple

**Comment by drvinceknight** [comment]
Yup.

**Comment by drvinceknight** [comment]
Have just pushed a commit (b4304b9c674459e3511a1bbf32342c7690c41780) that re calibrates the game after minimisation. It's a bit clunky with repeated code, see if you can improve it (don't spend too much time on it: I think when we go to the other form of NFG it'll be quite natural to do).

**Comment by drvinceknight** [comment]
Needs more tests.

**Comment by drvinceknight** [comment]
Is this implemented for lrs?

**Comment by theref** [comment]
Yes, it's sorted [here](https://github.com/theref/sage-game-theory/blob/16333/src/sage/game_theory/normal_form_game.py#L432).
