### ISSUE TITLE
Is it worth Cython-izing the Shapley value calculation?

### ISSUE THREAD

**Issue by drvinceknight** [theref/sage-game-theory#55]
Will this make it faster? Might be nice to test.

**Comment by theref** [comment]
Travis Scrimshaw has changed the method of calculating the shapley value to use `binomial`.

> With this change alone I got a 10~15% speedup

It now takes longer to create the game than solve it!! If we want to speed things up, we should take another look at how larger games can be created automatically and see if there are any improvements there.

Travis' change may require the docs to be altered though.

**Comment by drvinceknight** [comment]
This happened when we changed formulation (for N=15 I recall). If you stare
at the two formulae long enough you should be able to see why. No need to
look any further in to creating larger games (its an artificial exercise
anyway). If cythonizing is a minor tweak, it would be worth doing (longer
to create games than to solve them is a nice tagline).
