### ISSUE TITLE
Add repr method to normal form game

### ISSUE THREAD

**Issue by drvinceknight** [theref/sage-game-theory#60]

**Comment by theref** [comment]
I have already done this [here](https://github.com/theref/sage-game-theory/blob/16333/src/sage/game_theory/normal_form_game.py#L220)

**Comment by drvinceknight** [comment]
Ah yes of course. My bad.

**Comment by drvinceknight** [comment]
I wonder if what you have as well as something like "3 player normal form game" or similar is worth having.

**Comment by drvinceknight** [comment]
(Not sure about above, I like the simplicity of what you've got)

**Comment by drvinceknight** [comment]
Could be nice to have this repr return different things for different size games (so two player would return the payoff matrices or bi-matrix, higher would return what you have).
