### ISSUE TITLE
Refactor scaling

### ISSUE THREAD

**Issue by theref** [theref/sage-game-theory#68]
Probably need a separate `_scale_matrices` function. Would be cleaner and reusable.

Not sure what this should return though, depending on the other Gambit functions available this may be better scaling `self._strategy_profiles`

**Comment by drvinceknight** [comment]
I think it would just return the scaled matrices which are used as inputs in to the solve gambit function.

Not sure what you mean by scaling the strategy profiles.

Could we use Sage to check what ring a matrix is in and only apply the scaling if necessary?
