### ISSUE TITLE
Is it worth tweaking the `obtain_Nash` method to select LCP, lrs as default if packages are installed?

### ISSUE THREAD

**Issue by drvinceknight** [theref/sage-game-theory#71]
James: can you have a look around other packages and see if anything similar is done?

**Comment by theref** [comment]
My plan was to make it use enumeration as default, and throw a warning when things get too big. Anyone who installs gambit/lrs will know that enumeration isn't very good and will use the other options anyway.

I'll take a look though

**Comment by drvinceknight** [comment]
Mmmyeah... Not sure. In a way we for sure want lrs or gambit as default if they're there... Let me know if you find any relevant examples in Sage code.

**Comment by drvinceknight** [comment]
I've implemented this for now (mainly because I wrote about it in the docs)... Easy enough to take out if necessary.
