### ISSUE TITLE
Update installation instructions with binary as another option.

### ISSUE THREAD

**Issue by drvinceknight** [theref/sage-game-theory#75]

**Comment by theref** [comment]
installation of gambit instructions? is this so that it point at where you are hosting the tar?

**Comment by drvinceknight** [comment]
Yeah.

A user does not need to clone the repository if they don't care about
gambit...

On 26 June 2014 12:49, James Campbell notifications@github.com wrote:

> installation of gambit instructions? is this so that it point at where you
> are hosting the tar?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/theref/sage-game-theory/issues/75#issuecomment-47216270
> .

## 

Dr Vincent Knight
Cardiff School of Mathematics
Senghennydd Road,
Cardiff
CF24 4AG
(+44) 29 2087 5548
