### ISSUE TITLE
Does `payoff_matrices` make `_game_two_matrix` redundant?

### ISSUE THREAD

**Issue by drvinceknight** [theref/sage-game-theory#76]

**Comment by theref** [comment]
`_game_to_matrix` is used by a few different functions including `payoff_matrices`, we may be able to move all the code from `_game_to_matrix` into `payoff_matrices` and just call that function instead

**Comment by drvinceknight** [comment]
I think that might make sense... There were a couple of places in the code
where `_game_to_matrix` was being used but it would have been more
explanatory to use `payoff_matrices`...

On 26 June 2014 12:48, James Campbell notifications@github.com wrote:

> _game_to_matrix is used by a few different functions including
> payoff_matrices, we may be able to move all the code from _game_to_matrix
> into payoff_matrices and just call that function instead
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/theref/sage-game-theory/issues/76#issuecomment-47216187
> .

## 

Dr Vincent Knight
Cardiff School of Mathematics
Senghennydd Road,
Cardiff
CF24 4AG
(+44) 29 2087 5548

**Comment by theref** [comment]
ok, i'll fix that up
