### ISSUE TITLE
Getting different outputs from lrs, LCP and gambit

### ISSUE THREAD

**Issue by theref** [theref/sage-game-theory#77]
![screen shot 2014-06-26 at 09 27 21](https://cloud.githubusercontent.com/assets/4128101/3396283/28d903d4-fd0c-11e3-9e81-10bf891cde3b.png)

**Comment by theref** [comment]
Something weird went on between 22.20 and 22.30 last night?
![screen shot 2014-06-26 at 09 41 26](https://cloud.githubusercontent.com/assets/4128101/3396385/b3c6ae0a-fd0d-11e3-8b86-03518294f28e.png)

**Comment by theref** [comment]
Line 225: Enumeration's last strategy vector is `[(0.0, 0.0, 1.0, 0.0), (-10.9, 0.0, 0.0, 11.9, 0.0)]]`, this makes no sense, probabilities should never be negative

**Comment by theref** [comment]
A total of 9 of the errors were caused by negative probabilities, this has been fixed and those logs moved to an error.csv file

**Comment by drvinceknight** [comment]
We've had a lot more of these: can you take a look just to be sure.
