### ISSUE TITLE
`payoff_matrices` and `is_complete` don't necessarily agree

### ISSUE THREAD

**Issue by drvinceknight** [theref/sage-game-theory#78]
When you add a strategy to a gambit-syntax type game and call payoff_matrices it is populated with zeros.

We have two options:
- Get rid of `is_complete` and when a new strategy is created, utilities are automatically set to zero (so that we're in line with the payoff_matrices).
- Include a type error in payoff_matrices.

**Comment by theref** [comment]
I reckon a quick call to `is_complete` before `payoff_matrices` does it's stuff is the best option

**Comment by drvinceknight** [comment]
Cool. (Best option because otherwise no way to tell the difference between a game that has been fully populated or not.)

**Comment by theref** [comment]
Sorted by 33ac648
