### ISSUE TITLE
Create `_plot` method for matching game

### ISSUE THREAD

**Issue by drvinceknight** [theref/sage-game-theory#81]
This will just use the plot method of the corresponding `BiPartiteGraph` (another sage object).

**Comment by theref** [comment]
do we want a `plot` function or a `bi_partite` function? `bi_partite` would return the `BipartiteGraph` object on which you could then call `plot()`. I think it would be slightly more flexible.

**Comment by drvinceknight** [comment]
I agree with you.

**Comment by drvinceknight** [comment]
Actually do we want both? A plot that plots the graph and also a graph?
