### ISSUE TITLE
Investigate and potentially implement slightly better enumeration algorithm

### ISSUE THREAD

**Issue by drvinceknight** [theref/sage-game-theory#82]
Nice version of this algorithm is written in http://www.masfoundations.org/download.html

**Comment by theref** [comment]
This graph only shows games of size 10-30 because I wanted a quick analysis, but the results are fairly conclusive:
![compare_plot](https://cloud.githubusercontent.com/assets/4128101/3429033/882d4eb0-004c-11e4-92c3-c1deddf6af95.png)

**Comment by drvinceknight** [comment]
This look very promising: can you just confirm the gains by running both algorithms on the same machine.

**Comment by theref** [comment]
you were right, it's not quite as clear as we thought, this is the graph when run with the old algorithm
![compare_plot2](https://cloud.githubusercontent.com/assets/4128101/3429272/32a3d86a-0051-11e4-8f69-efd01b1b0bcc.png)
the new algorithm is definitely better, just not by as much as we may have thought

**Comment by drvinceknight** [comment]
Let's see the ratio instead of the difference?

**Comment by theref** [comment]
Ok, this is the graph we've all been waiting for. The y-axis i how many times faster the new algorithm was when run on my machine. These are some major improvements!
![ratio_plot](https://cloud.githubusercontent.com/assets/4128101/3430308/21636c50-0060-11e4-8af1-5a2f5dc30193.png)

**Comment by drvinceknight** [comment]
This looks awesome (for our records use the box plot code I've been using and throw that up here as well).

**Comment by theref** [comment]
![ratio_box_plot](https://cloud.githubusercontent.com/assets/4128101/3432535/bcffc504-0075-11e4-8069-049d93c8bd60.png)
