### ISSUE TITLE
Fix 16954 based on Karl's comments

### ISSUE THREAD

**Issue by drvinceknight** [theref/sage-game-theory#93]
Two sets:
- [ ] A bunch of doc stuff
- [ ] More about algorithm

**Comment by drvinceknight** [comment]
140342cdb41feb5911da8710150939bc17501e7e takes care of the stuff Karl raised with the parser, some details:
- The temp files: could you investigate @theref (if you ever get online again and/or get sage building again)?
- I think that his suggestion for speeding up the creation of `p1_strategies` makes the code less readable (and ultimately speed isn't the biggest factor with the parsing) so will ask when we respond on trac.
- Everything else is explainable.

**Comment by drvinceknight** [comment]
Ok I've had a pretty good go. I've got the actual support enumeration part to check through and address (the last big thing by Karl).

There are still some outstanding things though:
- [x] Move/copy docs to front matter (including in particular the airline example)
- [x] Check all commas etc
- [x] The LaTeX method: the fix suggested by Karl requires us to redo it as I've also changed the `str` method.
- [x] General fix / check of all examples
- [x] Check what happens to tmp files.
- [x] If we have any good tests/examples in `_methods` then copy them elsewhere (so that they appear in docs).

I'm going to leave those until I've finished with the support enumeration stuff (bigger job for later today or Sunday). Could you pick off some of them please @theref (in particular the tmp file one).

**Comment by theref** [comment]
Yeah will get onto tmp files, if it ever builds again that is.

**Comment by drvinceknight** [comment]
tmp files delete themselves:

```
Type:            function
String form:     <function tmp_filename at 0xb5ce8bfc>
File:            /home/vince/sage/local/lib/python2.7/site-packages/sage/misc/temporary_file.py
Definition:      tmp_filename(name='tmp_', ext='')
Docstring:
   Create and return a temporary file in
   "$HOME/.sage/temp/hostname/pid/"

   The temporary file is deleted automatically when Sage exits.
```

**Comment by drvinceknight** [comment]
Ok I've gone through the support enumeration part of the algorithm and basically have made fixes where they were needed (one really nice tweak based on Karl's suggestion).

I'm now going to go through the bullet point list I wrote above (just moving docs around).

Could you take a look at (you don't necessarily need to build Sage) the particular bullet point that starts with 'I just don't see how'. Let me know if you think that can be tidied at all: I don't I think I just need to explain it in the response to everything.

Should be able to push this to trac by tomorrow.

**Comment by theref** [comment]
I'm pretty sure the confusion lies in the naming of variables. Calling the iterable `k` instead of `p2_strategy` might make more sense in terms of the Matrix indices, however I prefer it as is.

To be fair though, I can't remember or work out why on worth we were taking the difference. This strikes me as something that I understood for a day, coded for a day, and then completely forgot. So a comment in there about why it's necessary probably wouldn't hurt.

**Comment by drvinceknight** [comment]
> me as something that I understood for a day, coded for a day, and then completely forgot

lol: story of my life.

c62ddc1f14086de751a299dc29450e67a29f9f8e just added comments and docstrings that I think explain it all.

**Comment by drvinceknight** [comment]
Ok: I'm about to push to trac. If you'd like me to hold fire so you can take a look let me know.
